---

- hosts: all
  become: true
  tasks:

  - name: intall update (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install httpd and php 
    yum
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "CentOS"  
     







  - name: install httpd and php  packages
    yum:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "CentOS"
